### ISSUE TITLE
Extension stopped hiding blue checkmarks on chrome pc, and kiwi(chromium based mobile browser)

### ISSUE THREAD

**Issue by Depact** [gsajith/blue-check-hider#2]
Screenshot of not hidden message and extension stats.
![image](https://github.com/gsajith/blue-check-hider/assets/19435553/a8c0ba75-f770-4b12-ba3a-c1cf9e3dfafd)
![image](https://github.com/gsajith/blue-check-hider/assets/19435553/1def6af4-b61c-4054-9ade-2f825ec8ba12)

P.S. Use this extension for a long time, and it made my previous twitter expirience so much better, and I'm thankful for it. Hoping for fix.

**Comment by GeorgeSpelvin** [comment]
The extension needs an update because it is ONLY geared to work on twitter.com but now Elmo has switched everything over to x.com URLs.

Still, my #1 wish for this extension is to -not- hide the few bluechecks I follow.  A follow should be whitelisted.

**Comment by Depact** [comment]
Can confirm. This problem apprear only with new url.
